{{- if .Values.configmap.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-configmap
data:
  backend-url: "{{ .Values.configmap.backendUrl }}"
{{- end }}




apiVersion: v1
kind: ConfigMap
metadata:
  name: intern-project-config
data:
  backend-url: backend-service


# Source: internproject/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-internproject-configmap
data:
  backendUrl: "backend-service"
---

