apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: {{ .Values.service.backendType }}
  selector:
    app: {{ template "fullname" . }}-backend
  ports:
  - protocol: TCP
    port: {{ .Values.service.backendPort }}
    targetPort: 5100



apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 5100
    targetPort: 5100

