apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-frontend
spec:
  type: {{ .Values.service.frontendType }}
  selector:
    app: {{ template "fullname" . }}-frontend
  ports:
  - protocol: TCP
    port: {{ .Values.service.frontendPort }}
    targetPort: 5200



apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 5200
    targetPort: 5200
    nodePort: 30006

