apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-backend
spec:
  type: {{ .Values.service.backendType }}
  selector:
    app: {{ template "fullname" . }}-backend
  ports:
  - protocol: TCP
    port: {{ .Values.service.backendPort }}
    targetPort: 5100
